"""remove_max_pool_size_from_user_recommendation_settings

Revision ID: 184976817123
Revises: 4c4e368472a8
Create Date: 2025-12-15 23:34:08.836188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184976817123'
down_revision: Union[str, Sequence[str], None] = '4c4e368472a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_recommendation_settings', 'max_pool_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_recommendation_settings', sa.Column('max_pool_size', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
