"""add_phone_number_make_email_nullable

Revision ID: 28772b1a241d
Revises: merge_auth_infographic
Create Date: 2025-12-09 21:48:44.851273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28772b1a241d'
down_revision: Union[str, Sequence[str], None] = 'merge_auth_infographic'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=32), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table_comment(
        'users',
        'User accounts with OAuth or local authentication',
        existing_comment='User accounts with OAuth authentication',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'User accounts with OAuth authentication',
        existing_comment='User accounts with OAuth or local authentication',
        schema=None
    )
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
