"""update_data_source_type

Revision ID: 373645360a44
Revises: 40f9b1e50a4b
Create Date: 2025-12-16 00:18:26.898228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373645360a44'
down_revision: Union[str, Sequence[str], None] = '40f9b1e50a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 创建枚举类型，如果不存在
    datasourcetype = sa.Enum('DAILY', 'STATIC', name='datasourcetype')
    datasourcetype.create(op.get_bind(), checkfirst=True)
    
    # 添加列，允许NULL
    op.add_column('data_sources', sa.Column('source_type', datasourcetype, nullable=True))
    
    # 更新现有数据
    op.execute("UPDATE data_sources SET source_type = CASE WHEN is_conference = true THEN 'STATIC'::datasourcetype ELSE 'DAILY'::datasourcetype END")
    
    # 设置为NOT NULL
    op.alter_column('data_sources', 'source_type', nullable=False)
    
    # 删除旧列
    op.drop_column('data_sources', 'is_conference')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('is_conference', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('data_sources', 'source_type')
    # ### end Alembic commands ###
