"""add_infographic_table

Revision ID: 377bbef65e4c
Revises: 76b6ff09472a
Create Date: 2025-12-15 15:13:15.936871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '377bbef65e4c'
down_revision: Union[str, Sequence[str], None] = '76b6ff09472a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infographics',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('paper_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infographics_paper_id'), 'infographics', ['paper_id'], unique=False)
    op.drop_index(op.f('ix_user_recommendation_pools_pool_date'), table_name='user_recommendation_pools')
    op.drop_index(op.f('ix_user_recommendation_pools_user_id'), table_name='user_recommendation_pools')
    op.drop_table('user_recommendation_pools')
    op.add_column('admin_pushed_content', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('admin_pushed_content', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('admin_pushed_content', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('admin_pushed_content', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_admin_pushed_content_paper_id'), table_name='admin_pushed_content')
    op.drop_index(op.f('idx_admin_pushed_content_priority'), table_name='admin_pushed_content')
    op.create_index(op.f('ix_admin_pushed_content_paper_id'), 'admin_pushed_content', ['paper_id'], unique=False)
    op.create_index(op.f('ix_admin_pushed_content_priority'), 'admin_pushed_content', ['priority'], unique=False)
    op.drop_index(op.f('idx_conf_pool_paper_id'), table_name='conference_recommendation_pool')
    op.drop_index(op.f('idx_conf_pool_source'), table_name='conference_recommendation_pool')
    op.create_index(op.f('ix_conference_recommendation_pool_paper_id'), 'conference_recommendation_pool', ['paper_id'], unique=False)
    op.create_index(op.f('ix_conference_recommendation_pool_source'), 'conference_recommendation_pool', ['source'], unique=False)
    op.add_column('content_generation_tasks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('content_generation_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('content_generation_tasks', 'progress',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('content_generation_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_content_generation_tasks_status'), table_name='content_generation_tasks')
    op.drop_index(op.f('idx_content_generation_tasks_user_id'), table_name='content_generation_tasks')
    op.create_index(op.f('ix_content_generation_tasks_status'), 'content_generation_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_content_generation_tasks_user_id'), 'content_generation_tasks', ['user_id'], unique=False)
    op.drop_index(op.f('ix_daily_recommendation_pool_archived'), table_name='daily_recommendation_pool')
    op.create_index(op.f('ix_daily_recommendation_pool_archived_at'), 'daily_recommendation_pool', ['archived_at'], unique=False)
    op.drop_column('daily_recommendation_pool', 'source_type')
    op.drop_index(op.f('idx_paper_translations_model_created'), table_name='paper_translations')
    op.drop_constraint(op.f('paper_translations_paper_id_key'), 'paper_translations', type_='unique')
    op.drop_index(op.f('ix_paper_translations_paper_id'), table_name='paper_translations')
    op.create_index(op.f('ix_paper_translations_paper_id'), 'paper_translations', ['paper_id'], unique=True)
    op.drop_index(op.f('idx_papers_categories_gin'), table_name='papers', postgresql_using='gin')
    op.drop_index(op.f('idx_papers_submitted_date'), table_name='papers')
    op.drop_constraint(op.f('uq_papers_arxiv_id'), 'papers', type_='unique')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    op.drop_constraint(op.f('uq_user_feedback_user_paper_type'), 'user_feedback', type_='unique')
    op.create_table_comment(
        'user_feedback',
        'Stores user-level explicit feedback for recommendation tuning',
        existing_comment=None,
        schema=None
    )
    op.add_column('user_generated_content', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('user_generated_content', 'is_shared',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_generated_content', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_generated_content', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_user_generated_content_paper_type'), table_name='user_generated_content')
    op.drop_index(op.f('idx_user_generated_content_user_created'), table_name='user_generated_content')
    op.create_index(op.f('ix_user_generated_content_paper_id'), 'user_generated_content', ['paper_id'], unique=False)
    op.create_index(op.f('ix_user_generated_content_user_id'), 'user_generated_content', ['user_id'], unique=False)
    op.drop_column('user_profiles', 'api_quota_used')
    op.drop_column('user_profiles', 'subscription_tier')
    op.drop_column('user_profiles', 'api_quota_limit')
    op.alter_column('user_recommendation_settings', 'arxiv_ratio',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_recommendation_settings', 'conference_ratio',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_recommendation_settings', 'enable_auto_generation',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_recommendation_settings', 'preferred_models',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_recommendation_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_recommendation_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('user_recommendation_settings', 'preferred_models',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_recommendation_settings', 'enable_auto_generation',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_recommendation_settings', 'conference_ratio',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_recommendation_settings', 'arxiv_ratio',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user_profiles', sa.Column('api_quota_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('subscription_tier', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('api_quota_used', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_generated_content_user_id'), table_name='user_generated_content')
    op.drop_index(op.f('ix_user_generated_content_paper_id'), table_name='user_generated_content')
    op.create_index(op.f('idx_user_generated_content_user_created'), 'user_generated_content', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_user_generated_content_paper_type'), 'user_generated_content', ['paper_id', 'content_type'], unique=False)
    op.alter_column('user_generated_content', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('user_generated_content', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_generated_content', 'is_shared',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user_generated_content', 'updated_at')
    op.drop_table_comment(
        'user_feedback',
        existing_comment='Stores user-level explicit feedback for recommendation tuning',
        schema=None
    )
    op.create_unique_constraint(op.f('uq_user_feedback_user_paper_type'), 'user_feedback', ['user_id', 'paper_id', 'feedback_type'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=False)
    op.create_unique_constraint(op.f('uq_papers_arxiv_id'), 'papers', ['arxiv_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_papers_submitted_date'), 'papers', ['submitted_date'], unique=False)
    op.create_index(op.f('idx_papers_categories_gin'), 'papers', ['categories'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_paper_translations_paper_id'), table_name='paper_translations')
    op.create_index(op.f('ix_paper_translations_paper_id'), 'paper_translations', ['paper_id'], unique=False)
    op.create_unique_constraint(op.f('paper_translations_paper_id_key'), 'paper_translations', ['paper_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_paper_translations_model_created'), 'paper_translations', ['model_name', 'created_at'], unique=False)
    op.add_column('daily_recommendation_pool', sa.Column('source_type', sa.VARCHAR(length=20), server_default=sa.text("'arxiv'::character varying"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_daily_recommendation_pool_archived_at'), table_name='daily_recommendation_pool')
    op.create_index(op.f('ix_daily_recommendation_pool_archived'), 'daily_recommendation_pool', ['archived_at'], unique=False)
    op.drop_index(op.f('ix_content_generation_tasks_user_id'), table_name='content_generation_tasks')
    op.drop_index(op.f('ix_content_generation_tasks_status'), table_name='content_generation_tasks')
    op.create_index(op.f('idx_content_generation_tasks_user_id'), 'content_generation_tasks', ['user_id'], unique=False)
    op.create_index(op.f('idx_content_generation_tasks_status'), 'content_generation_tasks', ['status'], unique=False)
    op.alter_column('content_generation_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('content_generation_tasks', 'progress',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content_generation_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('content_generation_tasks', 'updated_at')
    op.drop_index(op.f('ix_conference_recommendation_pool_source'), table_name='conference_recommendation_pool')
    op.drop_index(op.f('ix_conference_recommendation_pool_paper_id'), table_name='conference_recommendation_pool')
    op.create_index(op.f('idx_conf_pool_source'), 'conference_recommendation_pool', ['source'], unique=False)
    op.create_index(op.f('idx_conf_pool_paper_id'), 'conference_recommendation_pool', ['paper_id'], unique=False)
    op.drop_index(op.f('ix_admin_pushed_content_priority'), table_name='admin_pushed_content')
    op.drop_index(op.f('ix_admin_pushed_content_paper_id'), table_name='admin_pushed_content')
    op.create_index(op.f('idx_admin_pushed_content_priority'), 'admin_pushed_content', ['priority'], unique=False)
    op.create_index(op.f('idx_admin_pushed_content_paper_id'), 'admin_pushed_content', ['paper_id'], unique=False)
    op.alter_column('admin_pushed_content', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('admin_pushed_content', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('admin_pushed_content', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('admin_pushed_content', 'updated_at')
    op.create_table('user_recommendation_pools',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('pool_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('paper_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=False),
    sa.Column('scores', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=20), server_default=sa.text("'arxiv'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_recommendation_pools_pkey')),
    sa.UniqueConstraint('user_id', 'pool_date', 'source_type', name=op.f('user_recommendation_pools_user_id_pool_date_source_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_recommendation_pools_user_id'), 'user_recommendation_pools', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_recommendation_pools_pool_date'), 'user_recommendation_pools', ['pool_date'], unique=False)
    op.drop_index(op.f('ix_infographics_paper_id'), table_name='infographics')
    op.drop_table('infographics')
    # ### end Alembic commands ###
