"""add_source_key_to_user_recommendation_pool

Revision ID: 4656a9a4ead4
Revises: 373645360a44
Create Date: 2025-12-16 08:50:02.155853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4656a9a4ead4'
down_revision: Union[str, Sequence[str], None] = '373645360a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_recommendation_pools', sa.Column('source_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_user_recommendation_pools_source_key'), 'user_recommendation_pools', ['source_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_recommendation_pools_source_key'), table_name='user_recommendation_pools')
    op.drop_column('user_recommendation_pools', 'source_key')
    # ### end Alembic commands ###
