"""create_user_recommendation_pools_table_fixed

Revision ID: 4c4e368472a8
Revises: a23979cc1f5e
Create Date: 2025-12-15 23:28:34.962807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4e368472a8'
down_revision: Union[str, Sequence[str], None] = 'a23979cc1f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
