"""add paper_tts table

Revision ID: 5ee90d682b5b
Revises: 4656a9a4ead4
Create Date: 2025-12-18 21:42:16.321615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ee90d682b5b'
down_revision: Union[str, Sequence[str], None] = '4656a9a4ead4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_tts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('voice_model', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='存储论文TTS音频文件的元数据'
    )
    op.create_index(op.f('ix_paper_tts_paper_id'), 'paper_tts', ['paper_id'], unique=False)
    op.add_column('paper_translations', sa.Column('ai_interpretation', sa.Text(), nullable=True))
    op.add_column('paper_translations', sa.Column('infographic_html', sa.Text(), nullable=True))
    op.drop_column('user_profiles', 'embedding')
    op.alter_column('user_recommendation_pools', 'source_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index('idx_user_pool_date', 'user_recommendation_pools', ['user_id', 'pool_date'], unique=False)
    op.create_unique_constraint('uq_user_pool_date_source', 'user_recommendation_pools', ['user_id', 'pool_date', 'source_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_pool_date_source', 'user_recommendation_pools', type_='unique')
    op.drop_index('idx_user_pool_date', table_name='user_recommendation_pools')
    op.alter_column('user_recommendation_pools', 'source_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('user_profiles', sa.Column('embedding', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    op.drop_column('paper_translations', 'infographic_html')
    op.drop_column('paper_translations', 'ai_interpretation')
    op.drop_index(op.f('ix_paper_tts_paper_id'), table_name='paper_tts')
    op.drop_table('paper_tts')
    # ### end Alembic commands ###
