"""add_max_pool_size_to_user_recommendation_settings

Revision ID: 7e323e400b67
Revises: be77f5511895
Create Date: 2025-12-15 23:26:46.813451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e323e400b67'
down_revision: Union[str, Sequence[str], None] = 'be77f5511895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空字段
    op.add_column('user_recommendation_settings', sa.Column('max_pool_size', sa.Integer(), nullable=True))
    # 设置默认值
    op.execute("UPDATE user_recommendation_settings SET max_pool_size = 50 WHERE max_pool_size IS NULL")
    # 改为不可空
    op.alter_column('user_recommendation_settings', 'max_pool_size', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_recommendation_settings', 'max_pool_size')
    # ### end Alembic commands ###
