"""separate_translation_and_interpretation

Revision ID: be77f5511895
Revises: 377bbef65e4c
Create Date: 2025-12-15 21:46:35.083346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be77f5511895'
down_revision: Union[str, Sequence[str], None] = '377bbef65e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_interpretations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='存储论文的AI解读内容'
    )
    op.create_index(op.f('ix_paper_interpretations_paper_id'), 'paper_interpretations', ['paper_id'], unique=True)
    
    # 数据迁移: 使用 Python 生成 UUID
    import uuid
    from datetime import datetime
    
    connection = op.get_bind()
    
    # 获取需要迁移的数据
    result = connection.execute(sa.text("""
        SELECT paper_id, ai_interpretation, model_name, created_at, updated_at
        FROM paper_translations 
        WHERE ai_interpretation IS NOT NULL AND ai_interpretation != ''
    """))
    
    # 批量插入到新表
    for row in result:
        connection.execute(sa.text("""
            INSERT INTO paper_interpretations (id, paper_id, interpretation, language, model_name, created_at, updated_at)
            VALUES (:id, :paper_id, :interpretation, :language, :model_name, :created_at, :updated_at)
        """), {
            'id': str(uuid.uuid4()),
            'paper_id': str(row.paper_id),
            'interpretation': row.ai_interpretation,
            'language': 'zh',
            'model_name': row.model_name,
            'created_at': row.created_at,
            'updated_at': row.updated_at
        })
    
    op.create_table_comment(
        'paper_translations',
        '存储推荐池中论文的中文翻译',
        existing_comment='存储推荐池中论文的中文翻译和AI解读',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'paper_translations',
        '存储推荐池中论文的中文翻译和AI解读',
        existing_comment='存储推荐池中论文的中文翻译',
        schema=None
    )
    op.drop_index(op.f('ix_paper_interpretations_paper_id'), table_name='paper_interpretations')
    op.drop_table('paper_interpretations')
    # ### end Alembic commands ###
